### ISSUE TITLE
RFE: file triggers v2

### ISSUE THREAD

**Issue by pmatilai** [rpm-software-management/rpm#2655]
Real world usage has revealed various short-comings in the original file trigger design. With more subject experience under the belt now, the design needs to be revised, targetting minimal disruption to existing users.

Some of the issues include (to be updated as design is revised)
- [ ] Let packages decide/filter installed vs in-transaction files (#386)
- [x] Trigger arguments missing/non-sensical (#2755)
- [ ] Cumbersome API to Lua scriptlets, should use stdin too (depends on #2635)
- [ ] Reorganize and polish the documentation (#2860 and #2867)

**Comment by Conan-Kudo** [comment]
We should support all the same features for a file list entry here, which also means being able to handle regular expressions.

**Comment by dmnks** [comment]
> We should support all the same features for a file list entry here, which also means being able to handle regular expressions.

We don't support regexes in a `%files` entry, though, only globs.

**Comment by dmnks** [comment]
Let's track this in the respective GH project that already exists for this one: https://github.com/orgs/rpm-software-management/projects/16/views/1
